version: "3"
services:
  jekyll:
    image: ruby:3.3-alpine
    working_dir: /site
    command: sh -lc "apk add --no-cache build-base git && bundle install && bundle exec jekyll serve --host 0.0.0.0 --livereload --future"
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ./:/site
    restart: unless-stopped