version: "3"
services:
  site:
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 127.0.0.1:4000:4000
      - 127.0.0.1:35729:35729
      - 127.0.0.1:3000:3000
      - 127.0.0.1:8080:4000

